### ISSUE TITLE
[Front-end] Create Navigation Bar #Header

### ISSUE THREAD

**Issue by jumalaw98** [SpaceyaTech/Team-Berlin#25]
#### Description
As a developer
I need the header navigation bar
As reference from the [figma file](https://www.figma.com/file/UIPnjph81ynxLM3IUUdM8R/Spaceyatech-design-system?node-id=1%3A3)

#### Screenshots
![image](https://user-images.githubusercontent.com/41073697/198853130-69deb41f-5933-432b-a897-a40958708084.png)

#### Files
Here is link for reference, [Figma File](https://www.figma.com/file/UIPnjph81ynxLM3IUUdM8R/Spaceyatech-design-system?node-id=1%3A3) 

#### To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

#### Tasks & Acceptance Criteria 
The following nav links should be included 
- [ ] Home
- [ ] About Us
- [ ] Forum 
- [ ] Event 
- [ ] Our Blog
- [ ] Jobs

**Comment by daveclinton** [comment]
@jumalaw98 can i action on this issue? If yes, You can assign me.

**Comment by antomuangigitau** [comment]
@jumalaw98 Hey you could assign this issue
