### ISSUE TITLE
[Frontend] - Create the sign-in component 

### ISSUE THREAD

**Issue by jumalaw98** [SpaceyaTech/Team-Berlin#36]
## Description

As a developer
With regards to the screenshot below and the [figma file](https://www.figma.com/file/UIPnjph81ynxLM3IUUdM8R/Spaceyatech-design-system?node-id=472%3A5732) 
Assets on figma file 

## Screenshot 
![image](https://user-images.githubusercontent.com/41073697/200067561-44e00c34-c021-40c4-a166-606f33201816.png)

## Reference
- [Figma design](https://www.figma.com/file/UIPnjph81ynxLM3IUUdM8R/Spaceyatech-design-system?node-id=472%3A5732)

**Comment by KatarinaChavkova** [comment]
Hi, can be this issue assigned to me?

**Comment by NikolaGundzikova** [comment]
Hello, I have solved this issue. Can you assign me, please?
