### ISSUE TITLE
[Frontend] Creating signup component 

### ISSUE THREAD

**Issue by jumalaw98** [SpaceyaTech/Team-Berlin#37]
## Description
As a developer
With regards to the screenshot below and the [figma file](https://www.figma.com/file/UIPnjph81ynxLM3IUUdM8R/Spaceyatech-design-system?node-id=472%3A5732)
Assets on figma file

## Screenshot 
![image](https://user-images.githubusercontent.com/41073697/200068828-3cc6dfb4-a552-47ea-8f6a-bae93c3db9d4.png)

## Reference
- [Figma design](https://www.figma.com/file/UIPnjph81ynxLM3IUUdM8R/Spaceyatech-design-system?node-id=472%3A5732)

**Comment by Abdirizaks12** [comment]
assign me please.

**Comment by jumalaw98** [comment]
I will like to assign you on this, but we have a pending issue that need to be resolve "constant and variable" of the project,

**Comment by daveclinton** [comment]
> I will like to assign you on this, but we have a pending issue that need to be resolve "constant and variable" of the project,

@jumalaw98 the constant and variables depends on the css framework that's going to be used.

**Comment by byronkenoly** [comment]
![signup (2)](https://user-images.githubusercontent.com/62793290/205707540-4001f792-7a9a-44c1-9cd9-9a4a806a801e.png)

did everything render correctly on your side @Abdirizaks12 ?

**Comment by Abdirizaks12** [comment]
@byronkenoly yes on my side it was working well.. I can see also the Navbar is affected.

**Comment by byronkenoly** [comment]
Who did the review before merging it with the pre-dev branch? @Abdirizaks12
