### ISSUE TITLE
[Frontend]- Installation and configuration of Tailwind to the project 

### ISSUE THREAD

**Issue by jumalaw98** [SpaceyaTech/Team-Berlin#42]
As a developer

Install the tailwind css framework
No third parties libraries are allowed 

## Additional Information
- [Tailwind Documentation ](https://tailwindcss.com/docs/installation)

**Comment by daveclinton** [comment]
I have actioned on this issue because it is a blocker for the rest of the issues.

**Comment by daveclinton** [comment]
This issue has been actioned on Pull Request https://github.com/SpaceyaTech/Team-Berlin-React/pull/46
